# Generated by Django 3.1.3 on 2020-11-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.TextField(max_length=120)),
                ('nombre', models.TextField(max_length=120)),
                ('recepcion', models.TextField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='formulario',
        ),
    ]
