# Generated by Django 3.1.3 on 2020-11-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quesito', '0002_auto_20201104_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='recepcion',
            new_name='contraseña',
        ),
    ]
