# Generated by Django 3.1.3 on 2020-11-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesito', '0003_auto_20201104_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.TextField(max_length=120)),
                ('descripcion', models.TextField(max_length=280)),
                ('img', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
