# Generated by Django 3.1.3 on 2020-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesito', '0004_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precioCosto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='precioVenta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
